### DISCUSSION TITLE
Devika Docker Compose for Ollama External Server

### DISCUSSION THREAD

**Discussion by hqnicolas** [stitionai/devika#552] [Show and tell]
Devika Version: May Update: Devika [a861328](https://github.com/stitionai/devika/commit/a861328a873d963583af2cf4e64452415dfecdb1)
Ollama Version on docker composer 
`easy to deploy`
https://github.com/hqnicolas/devika
- Latest:
[May 2024 v0.0.3](https://github.com/hqnicolas/devika/tree/v0.0.3)
- Old Releases:
[April 2024  v0.0.2 ](https://github.com/hqnicolas/devika/tree/v0.0.2)
[March 2024 v0.0.1](https://github.com/hqnicolas/devika/tree/v0.0.1)

**Comment by KTheMan** [comment]
I see the note on your latest release, 0.0.3:
> Freeze version that works with external Ollama

I used the main branch to pull from and haven't had any success getting external ollama to work - should I have pulled down 0.0.3?

**Reply by hqnicolas** [reply]
It doesn't found the ollama server?

How config.toml ollama url was setup?

How environment was config inside docker-compose.yaml?

**Reply by KTheMan** [reply]
No, unfortunately not.

**config.toml**
```toml
[STORAGE]
SQLITE_DB = "data/db/devika.db"
SCREENSHOTS_DIR = "data/screenshots"
PDFS_DIR = "data/pdfs"
PROJECTS_DIR = "data/projects"
LOGS_DIR = "data/logs"
REPOS_DIR = "data/repos"
WEB_SEARCH = "ddgs"

[API_KEYS]
BING = "<YOUR_BING_API_KEY>"
GOOGLE_SEARCH = "<GOOGLE_SEARCH_API_KEY>"
GOOGLE_SEARCH_ENGINE_ID = "<GOOGLE_SEARCH_ID>"
CLAUDE = "<YOUR_CLAUDE_API_KEY>"
OPENAI = "ollama"
GEMINI = "<YOUR_GEMINI_API_KEY>"
MISTRAL = "<YOUR_MISTRAL_API_KEY>"
GROQ = "<YOUR_GROQ_API_KEY>"
NETLIFY = "<YOUR_NETLIFY_API_KEY>"

[API_ENDPOINTS]
BING = "https://api.bing.microsoft.com/v7.0/search"
GOOGLE = "https://www.googleapis.com/customsearch/v1"
OLLAMA = "http://192.168.1.115:11434"
OPENAI = "http://192.168.1.115:11434/v1"

[LOGGING]
LOG_REST_API = "true"
LOG_PROMPTS = "false"

[TIMEOUT]
INFERENCE = 360

```

**docker-compose.yaml**
```yaml
version: "3.9"

services:
  devika-backend-engine:
    build:
      context: .
      dockerfile: devika.dockerfile
    expose:
      - 1337
    ports:
      - 1337:1337
    environment:
      - OLLAMA_HOST=http://192.168.1.115:11434
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:1337/ || exit 1"]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - devika-backend-dbstore:/home/nonroot/devika/db
      - /DATA/Downloads/devikaprojects:/home/nonroot/devika/data/projects
    networks:
      - devika-subnetwork

  devika-frontend-app:
    build:
      context: .
      dockerfile: app.dockerfile
      args:
        - VITE_API_BASE_URL=http://127.0.0.1:1337
    depends_on:
      - devika-backend-engine
    expose:
      - 3000
    ports:
      - 3000:3000
    networks:
      - devika-subnetwork

networks:
  devika-subnetwork:

volumes:
  devika-backend-dbstore:
```
