### ISSUE TITLE
Using devika on Docker Compose With External Ollama Server

### ISSUE THREAD

**Issue by hqnicolas** [stitionai/devika#257]
congratulations, this devika project is an amazing piece of art!

All changes made to [hqnicolas devika](https://github.com/hqnicolas/devika)

Remove the Ollama server from docker compose 

_EDIT:_ **docker-compose.yaml**

```
version: "3.9"

services:
  devika-backend-engine:
    build:
      context: .
      dockerfile: devika.dockerfile
    expose:
      - 1337
    ports:
      - 1337:1337
    environment:
      - OLLAMA_HOST=http://192.168.0.21:11434
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:1337/ || exit 1"]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - devika-backend-dbstore:/home/nonroot/devika/db
    networks:
      - devika-subnetwork

  devika-frontend-app:
    build:
      context: .
      dockerfile: app.dockerfile
      args:
        - VITE_API_BASE_URL=http://127.0.0.1:1337
    depends_on:
      - devika-backend-engine
    expose:
      - 3000
    ports:
      - 3000:3000
    networks:
      - devika-subnetwork

networks:
  devika-subnetwork:

volumes:
  devika-backend-dbstore:
```

Stop Messing with user on docker compose!

_EDIT:_ **devika.dockerfile**
```
FROM debian:12

# setting up os env
USER root
WORKDIR /home/nonroot/devika

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

# setting up python3
RUN apt-get update && apt-get upgrade
RUN apt-get install -y build-essential software-properties-common curl sudo wget git
RUN apt-get install -y python3 python3-pip
RUN curl -fsSL https://astral.sh/uv/install.sh | sudo -E bash -
RUN $HOME/.cargo/bin/uv venv
ENV PATH="/home/nonroot/devika/.venv/bin:$HOME/.cargo/bin:$PATH"

# copy devika python engine only
RUN $HOME/.cargo/bin/uv venv
COPY requirements.txt /home/nonroot/devika/
RUN UV_HTTP_TIMEOUT=100000 $HOME/.cargo/bin/uv pip install -r requirements.txt 
RUN playwright install --with-deps chromium

COPY src /home/nonroot/devika/src
COPY config.toml /home/nonroot/devika/
COPY devika.py /home/nonroot/devika/
RUN chown -R root:root /home/nonroot/devika

USER root
WORKDIR /home/nonroot/devika
ENV PATH="/home/nonroot/devika/.venv/bin:$HOME/.cargo/bin:$PATH"
RUN mkdir /home/nonroot/devika/db

ENTRYPOINT [ "python3", "-m", "devika" ]
```
Make Sure that your Ollama server have this Models:
- openchat:7b-v3.5-1210-q5_K_M (4.8GB)
- mistral-openorca:7b-q5_K_M (4.8GB)
- qwen:14b-chat-v1.5-q4_K_M (8.6GB)

Put your Bing API From
BING = "https://api.bing.microsoft.com/v7.0/search"
